[toolchain]

[features]
resolution = true
skip-lint = false
solana = []

[programs.localnet]
solana_email_identity = "2RheqZFzSkEabsVcxg7zLJ8wqwadwyUvcYhi1gK2H28j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "./fixed-deploy-keypair.json"

[scripts]
test = "mocha"

[build]
sbf-flags = ["--no-separate-code"]