[toolchain]

[features]
resolution = true
skip-lint = false
solana = []

[programs.localnet]
solana_email_identity = "FCN9dmSwzfY6ygooW1ZeQaSxhc5QqtdBMFg5cnxPe4PC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha --config tests/mocha.opts tests/**/*.ts --timeout 10000"

[build]
sbf-flags = ["--no-separate-code"]