name: Anchor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$curl -sSfL https://release.solana.com/v1.18.2/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --locked --force

      - name: Install Node dependencies
        run: yarn install

      - name: Build the Anchor program
        run: anchor build

      - name: Run tests
        run: anchor test