name: Anchor CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo git repositories
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      # Install the Solana CLI using the command from Solana docs.
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # Set up a fixed deployment wallet using a secret.
      - name: Set up Anchor Wallet from Secret
        run: |
          mkdir -p ~/.config/solana
          echo "$DEPLOY_KEYPAIR" > ~/.config/solana/id.json
          echo "ANCHOR_WALLET=~/.config/solana/id.json" >> $GITHUB_ENV
        env:
          DEPLOY_KEYPAIR: ${{ secrets.DEPLOY_KEYPAIR }}


      # Generate a Solana wallet keypair if one doesn't exist
      #- name: Generate Solana Keypair
      #  run: |
      #  mkdir -p ~/.config/solana
      #   if [ ! -f ~/.config/solana/id.json ]; then
      #     solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json
      #   fi

      # Install the Anchor CLI (adjust version if needed).
      - name: Install Anchor CLI
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.0 anchor-cli --locked --force

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'

      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node dependencies
        run: yarn install

      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      # Set the SBF_RUSTC environment variable.
      - name: Set SBF_RUSTC environment variable
        run: echo "SBF_RUSTC=$(which rustc)" >> $GITHUB_ENV

      - name: Build the Anchor program
        run: anchor build

      - name: Start Solana test validator
        run: |
          solana-test-validator --reset &
          sleep 20

      - name: Deploy the Anchor program
        run: anchor deploy

      - name: Run tests
        run: anchor test
